kind: pipeline
type: docker
name: script-firefly-iii-budget-resp

steps:
  - name: Build clear
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker build . -t vepl/script-firefly-iii-budget-resp:latest
      - echo ${DOCKER_PAT} | docker login -u vepl
      - docker push  vepl/script-firefly-iii-budget-resp:latest
    environment:
      DOCKER_PAT:
        from_secret: DOCKER_PAT
    when:
      branch:
      - master

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock
